CREATE TABLE attributes(name VARCHAR(50),
                        domain VARCHAR(256),
                        representionRule TEXT,
                        collectionOf VARCHAR(307),
                        validity integer,
                        calculation TEXT,
                        eager_calculation boolean,
                        input_attribute_ids VARCHAR(36)[],
                        revisioning boolean,
                        revisionCount integer,
                        lastRevisionDate timestamp);
