title: LinkedRecords
description: A documentation site for https://github.com/wolfoo2931/linkedrecords
theme: just-the-docs

url: https://wolfoo2931.github.io/linkedrecords

aux_links:
  LinkedRecords on GitHub:
    - https://github.com/wolfoo2931/linkedrecords/

callouts:
  note:
    title: Note
    color: blue
