name: Fixme-Alert

permissions:
  contents: read
  pull-requests: read

on:
  workflow_dispatch:
    inputs: {}
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, develop ]

jobs:
  fixmes:
    name: FIXME check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: bbugh/action-fixme-check@master
      with:
      	terms: 'WIP|FIXME|TODO'
      	case-sensitive: false